// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl29NqcDoqIcmHu7pq2FXOc6_lYrqkNDI',
    appId: '1:821813732686:web:35d83da188c1df29f9ea1f',
    messagingSenderId: '821813732686',
    projectId: 'my-product-ff8d3',
    authDomain: 'my-product-ff8d3.firebaseapp.com',
    storageBucket: 'my-product-ff8d3.appspot.com',
    measurementId: 'G-7RB54LEN8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKFC_X6Jx4NONGvNs8X65r8Jayx0Hqhs',
    appId: '1:821813732686:android:eeb5b9d98143e229f9ea1f',
    messagingSenderId: '821813732686',
    projectId: 'my-product-ff8d3',
    storageBucket: 'my-product-ff8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8FvJCodT3v9RUeD8HAmRzxr9sDHHstY',
    appId: '1:821813732686:ios:1aa1583a1760e9aaf9ea1f',
    messagingSenderId: '821813732686',
    projectId: 'my-product-ff8d3',
    storageBucket: 'my-product-ff8d3.appspot.com',
    iosBundleId: 'com.example.firebaseex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs8FvJCodT3v9RUeD8HAmRzxr9sDHHstY',
    appId: '1:821813732686:ios:1aa1583a1760e9aaf9ea1f',
    messagingSenderId: '821813732686',
    projectId: 'my-product-ff8d3',
    storageBucket: 'my-product-ff8d3.appspot.com',
    iosBundleId: 'com.example.firebaseex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl29NqcDoqIcmHu7pq2FXOc6_lYrqkNDI',
    appId: '1:821813732686:web:fa9a1b09bbd1ddfcf9ea1f',
    messagingSenderId: '821813732686',
    projectId: 'my-product-ff8d3',
    authDomain: 'my-product-ff8d3.firebaseapp.com',
    storageBucket: 'my-product-ff8d3.appspot.com',
    measurementId: 'G-974M1RKRC1',
  );
}
